import type { GuideDefinition } from '../types';

import { ensurePanelAndActivate } from '@/composables/useDockApi';

export const proofreaderGuide: GuideDefinition = {
  role: 'proofreader',
  title: '校核员校审向导',
  description: '了解如何接收设计提资、完成三维校核并提交下一节点。',
  steps: [
    {
      id: 'ribbon-review-tab',
      targetSelector: '[data-ribbon-tab="review"]',
      title: '校审功能区',
      description: '所有校审相关操作都在「校审」标签页中，先从这里进入工作区。',
      placement: 'bottom',
    },
    {
      id: 'review-start-btn',
      targetSelector: '[data-command="review.start"]',
      title: '查看待校核任务',
      description: '点击「开始校审」进入待处理任务列表，查看分配给你的校核任务。',
      placement: 'bottom',
    },
    {
      id: 'reviewer-task-list',
      targetSelector: '[data-panel="reviewerTasks"]',
      targetPanelId: 'reviewerTasks',
      title: '待校核任务列表',
      description: '这里列出了所有分配给你的待校核任务。点击任务即可进入校审面板。',
      placement: 'left',
      onBeforeShow: () => ensurePanelAndActivate('reviewerTasks'),
    },
    {
      id: 'review-panel-header',
      targetSelector: '[data-guide="review-panel-header"]',
      targetPanelId: 'review',
      title: '进入校审面板',
      description: '打开任务后，你会在这里看到任务标题、当前流程节点、任务构件过滤等核心上下文。',
      placement: 'bottom',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'workflow-step-bar',
      targetSelector: '[data-guide="workflow-step-bar"]',
      targetPanelId: 'review',
      title: '工作流进度',
      description: '步骤条显示当前任务所处的审批阶段：编制 → 校核 → 审核 → 批准。当前高亮的是你需要处理的节点。',
      placement: 'bottom',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'review-panel-tools',
      targetSelector: '[data-guide="review-panel-tools"]',
      targetPanelId: 'review',
      title: '批注与测量工具',
      description: '在这里可以直接启动文字批注、云线批注、矩形批注和测量，用于记录发现的问题。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'confirm-data-btn',
      targetSelector: '[data-command="review.confirm"]',
      targetPanelId: 'review',
      title: '确认当前数据',
      description: '完成批注与测量后，点击这里将当前这批三维校核数据保存到确认记录。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'confirmed-records',
      targetSelector: '[data-testid="review-workbench-confirmed-records-zone"]',
      targetPanelId: 'review',
      title: '查看确认记录',
      description: '保存后的记录会出现在这里，你可以回看每一批已确认的批注数量、测量数量和备注。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'submit-or-return',
      targetSelector: '[data-guide="workflow-actions"]',
      targetPanelId: 'review',
      title: '提交或驳回',
      description: '校核完成后，可以提交到审核节点，也可以驳回到设计节点要求修改。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
  ],
};

export const reviewerGuide: GuideDefinition = {
  role: 'reviewer',
  title: '审核员校审向导',
  description: '了解如何读取校核结果、复核三维内容并做出审核决策。',
  steps: [
    {
      id: 'ribbon-review-tab',
      targetSelector: '[data-ribbon-tab="review"]',
      title: '校审功能区',
      description: '审核功能在「校审」标签页中，点击切换到此标签页。',
      placement: 'bottom',
    },
    {
      id: 'reviewer-task-list',
      targetSelector: '[data-panel="reviewerTasks"]',
      targetPanelId: 'reviewerTasks',
      title: '待审核任务',
      description: '这里列出了经过校核后提交给你审核的任务。点击任务可进入详情。',
      placement: 'left',
      onBeforeShow: () => ensurePanelAndActivate('reviewerTasks'),
    },
    {
      id: 'review-panel',
      targetSelector: '[data-panel="review"]',
      targetPanelId: 'review',
      title: '审核面板',
      description: '在审核面板中查看任务上下文、当前节点与核心审核动作。',
      placement: 'left',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'confirmed-records',
      targetSelector: '[data-testid="review-workbench-confirmed-records-zone"]',
      targetPanelId: 'review',
      title: '确认记录与三维数据',
      description: '这里集中展示校核人已确认保存的批注、测量和备注，是审核时首先需要关注的内容。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'annotation-list',
      targetSelector: '[data-guide="annotation-list-zone"]',
      targetPanelId: 'review',
      title: '批注列表与评论',
      description: '展开具体批注后，可以查看批注详情、评论线程以及定位操作。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'review-panel-tools',
      targetSelector: '[data-guide="review-panel-tools"]',
      targetPanelId: 'review',
      title: '继续补充批注或测量',
      description: '如果审核过程中发现新的问题，也可以在这里直接继续发起批注、云线或测量。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'submit-or-return',
      targetSelector: '[data-guide="workflow-actions"]',
      targetPanelId: 'review',
      title: '审核决策',
      description: '审核通过可提交到批准，发现问题可驳回到设计或校核节点，要求相关人员修改。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
  ],
};

export const managerGuide: GuideDefinition = {
  role: 'manager',
  title: '批准人校审向导',
  description: '了解如何查看完整校审链路并做出最终批准决策。',
  steps: [
    {
      id: 'ribbon-review-tab',
      targetSelector: '[data-ribbon-tab="review"]',
      title: '校审功能区',
      description: '批准操作在「校审」标签页中，点击切换到此标签页。',
      placement: 'bottom',
    },
    {
      id: 'reviewer-task-list',
      targetSelector: '[data-panel="reviewerTasks"]',
      targetPanelId: 'reviewerTasks',
      title: '待批准任务',
      description: '经过校核和审核后的任务会出现在这里，等待你的最终批准。',
      placement: 'left',
      onBeforeShow: () => ensurePanelAndActivate('reviewerTasks'),
    },
    {
      id: 'review-panel',
      targetSelector: '[data-panel="review"]',
      targetPanelId: 'review',
      title: '审批面板',
      description: '在这里查看完整流程、确认记录、批注意见和附件，再做最终判断。',
      placement: 'left',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'confirmed-records',
      targetSelector: '[data-testid="review-workbench-confirmed-records-zone"]',
      targetPanelId: 'review',
      title: '已确认记录',
      description: '批准前建议重点复查确认记录，确认批注、测量和备注都已经闭环。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
    {
      id: 'finalize-decision',
      targetSelector: '[data-guide="workflow-actions"]',
      targetPanelId: 'review',
      title: '最终决策',
      description: '你可以最终批准完成流程，也可以驳回要求相关环节继续修改。',
      placement: 'top',
      onBeforeShow: () => ensurePanelAndActivate('review'),
    },
  ],
};
