import {
  Bug,
  Calculator,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Download,
  Eye,
  File,
  FileText,
  FolderOpen,
  HelpCircle,
  Info,
  LayoutPanelLeft,
  List,
  MessageSquareText,
  Pencil,
  Redo2,
  Ruler,
  Search,
  Settings,
  ShieldQuestion,
  SquarePen,
  Tag,
  Trash2,
  TreePine,
  Undo2,
  Wrench,
  GitCompare,
} from 'lucide-vue-next';

export const ribbonIcons = {
  bug: Bug,
  calculator: Calculator,
  check_circle: CheckCircle,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  clipboard_check: ClipboardCheck,
  clipboard_list: ClipboardList,
  compare: GitCompare,
  download: Download,
  eye: Eye,
  file: File,
  file_text: FileText,
  folder_open: FolderOpen,
  help: HelpCircle,
  info: Info,
  layout_left: LayoutPanelLeft,
  list: List,
  note: MessageSquareText,
  pencil: Pencil,
  redo: Redo2,
  ruler: Ruler,
  search: Search,
  settings: Settings,
  question: ShieldQuestion,
  square_pen: SquarePen,
  tag: Tag,
  trash: Trash2,
  tree: TreePine,
  undo: Undo2,
  component: Wrench,
} as const;

export type RibbonIconName = keyof typeof ribbonIcons;
