import {
  Bug,
  Calculator,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Download,
  File,
  FolderOpen,
  HelpCircle,
  Info,
  LayoutPanelLeft,
  MessageSquareText,
  Pencil,
  Redo2,
  Ruler,
  Search,
  Settings,
  ShieldQuestion,
  SquarePen,
  Trash2,
  TreePine,
  Undo2,
} from 'lucide-vue-next';

export const ribbonIcons = {
  bug: Bug,
  calculator: Calculator,
  check_circle: CheckCircle,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  clipboard_check: ClipboardCheck,
  clipboard_list: ClipboardList,
  download: Download,
  file: File,
  folder_open: FolderOpen,
  help: HelpCircle,
  info: Info,
  layout_left: LayoutPanelLeft,
  note: MessageSquareText,
  pencil: Pencil,
  redo: Redo2,
  ruler: Ruler,
  search: Search,
  settings: Settings,
  question: ShieldQuestion,
  square_pen: SquarePen,
  trash: Trash2,
  tree: TreePine,
  undo: Undo2,
} as const;

export type RibbonIconName = keyof typeof ribbonIcons;
