import '@/assets/tailwind.css';
import '@/assets/main.scss';
import '@/utils/three/patches/applyMeshLineShaderCompat';
import 'dockview-vue/dist/styles/dockview.css';
import { createApp } from 'vue';

import { VueQueryPlugin } from '@tanstack/vue-query';

import App from '@/App.vue';
import BenchmarkView from '@/components/debug/BenchmarkView.vue';
import AnnotationPanelDock from '@/components/dock_panels/AnnotationPanelDock.vue';
import AnnotationStylePanelDock from '@/components/dock_panels/AnnotationStylePanelDock.vue';
import ConsolePanelDock from '@/components/dock_panels/ConsolePanelDock.vue';
import DashboardPanelDock from '@/components/dock_panels/DashboardPanelDock.vue';
import DesignerTaskListPanelDock from '@/components/dock_panels/DesignerTaskListPanelDock.vue';
import DimensionPanelDock from '@/components/dock_panels/DimensionPanelDock.vue';
import DimensionStylePanelDock from '@/components/dock_panels/DimensionStylePanelDock.vue';
import DtxMaterialConfigPanelDock from '@/components/dock_panels/DtxMaterialConfigPanelDock.vue';
import HydraulicPanelDock from '@/components/dock_panels/HydraulicPanelDock.vue';
import InitiateReviewPanelDock from '@/components/dock_panels/InitiateReviewPanelDock.vue';
import ManagerPanelDock from '@/components/dock_panels/ManagerPanelDock.vue';
import MbdPipePanelDock from '@/components/dock_panels/MbdPipePanelDock.vue';
import MeasurementPanelDock from '@/components/dock_panels/MeasurementPanelDock.vue';
import ModelExportPanelDock from '@/components/dock_panels/ModelExportPanelDock.vue';
import ModelTreePanelDock from '@/components/dock_panels/ModelTreePanelDock.vue';
import ParquetDebugPanelDock from '@/components/dock_panels/ParquetDebugPanelDock.vue';
import PropertiesPanelDock from '@/components/dock_panels/PropertiesPanelDock.vue';
import PtsetPanelDock from '@/components/dock_panels/PtsetPanelDock.vue';
import ResubmissionTaskListPanelDock from '@/components/dock_panels/ResubmissionTaskListPanelDock.vue';
import ReviewerTaskListPanelDock from '@/components/dock_panels/ReviewerTaskListPanelDock.vue';
import ReviewPanelDock from '@/components/dock_panels/ReviewPanelDock.vue';
import RoomStatusPanelDock from '@/components/dock_panels/RoomStatusPanelDock.vue';
import TaskCreationPanelDock from '@/components/dock_panels/TaskCreationPanelDock.vue';
import TaskMonitorPanelDock from '@/components/dock_panels/TaskMonitorPanelDock.vue';
import ViewerPanel from '@/components/dock_panels/ViewerPanel.vue';
import vuetify from '@/plugins/vuetify';

const app = createApp(App);

app.use(VueQueryPlugin);
app.component('ViewerPanel', ViewerPanel);
app.component('ModelTreePanel', ModelTreePanelDock);
app.component('MeasurementPanel', MeasurementPanelDock);
app.component('DimensionPanel', DimensionPanelDock);
app.component('AnnotationPanel', AnnotationPanelDock);
app.component('AnnotationStylePanel', AnnotationStylePanelDock);
app.component('HydraulicPanel', HydraulicPanelDock);
app.component('ManagerPanel', ManagerPanelDock);
app.component('PropertiesPanel', PropertiesPanelDock);
app.component('PtsetPanel', PtsetPanelDock);
app.component('MbdPipePanel', MbdPipePanelDock);
app.component('ReviewPanel', ReviewPanelDock);
app.component('InitiateReviewPanel', InitiateReviewPanelDock);
app.component('ReviewerTaskListPanel', ReviewerTaskListPanelDock);
app.component('DesignerTaskListPanel', DesignerTaskListPanelDock);
app.component('ResubmissionTaskListPanel', ResubmissionTaskListPanelDock);
app.component('TaskMonitorPanel', TaskMonitorPanelDock);
app.component('TaskCreationPanel', TaskCreationPanelDock);
app.component('ModelExportPanel', ModelExportPanelDock);
app.component('ConsolePanel', ConsolePanelDock);
app.component('ParquetDebugPanel', ParquetDebugPanelDock);
app.component('RoomStatusPanel', RoomStatusPanelDock);
app.component('DimensionStylePanel', DimensionStylePanelDock);
app.component('DtxMaterialConfigPanel', DtxMaterialConfigPanelDock);
app.component('DashboardPanel', DashboardPanelDock);
app.component('BenchmarkView', BenchmarkView);

app.use(vuetify).mount('#app');
