import {
  Activity,
  Box,
  Bug,
  Calculator,
  CircleDot,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Database,
  Download,
  Eye,
  File,
  FileText,
  FolderOpen,
  Locate,
  HelpCircle,
  Info,
  LayoutPanelLeft,
  Link2,
  List,
  MessageSquareText,
  Monitor,
  MoveHorizontal,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Pencil,
  Plus,
  Redo2,
  Ruler,
  Search,
  Settings,
  ShieldQuestion,
  Spline,
  SquarePen,
  Tag,
  Trash2,
  TrendingUp,
  TreePine,
  Undo2,
  Wrench,
  Zap,
  GitCompare,
  Terminal,
} from 'lucide-vue-next';

export const ribbonIcons = {
  activity: Activity,
  bug: Bug,
  calculator: Calculator,
  check_circle: CheckCircle,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  clipboard_check: ClipboardCheck,
  clipboard_list: ClipboardList,
  compare: GitCompare,
  console: Terminal,
  cube: Box,
  database: Database,
  download: Download,
  eye: Eye,
  file: File,
  file_text: FileText,
  folder_open: FolderOpen,
  help: HelpCircle,
  info: Info,
  layout_left: LayoutPanelLeft,
  link: Link2,
  list: List,
  locate: Locate,
  monitor: Monitor,
  move_horizontal: MoveHorizontal,
  note: MessageSquareText,
  panel_bottom: PanelBottom,
  panel_left: PanelLeft,
  panel_right: PanelRight,
  pencil: Pencil,
  plus: Plus,
  redo: Redo2,
  ruler: Ruler,
  ruler_combined: Ruler,
  search: Search,
  settings: Settings,
  question: ShieldQuestion,
  circle_dot: CircleDot,
  spline: Spline,
  square_pen: SquarePen,
  tag: Tag,
  trending_up: TrendingUp,
  trash: Trash2,
  tree: TreePine,
  undo: Undo2,
  component: Wrench,
  zap: Zap,
} as const;

export type RibbonIconName = keyof typeof ribbonIcons;
